<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-09-01">

<title>Lead_Content and Freedom_GDP</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Lead and Freedom_GDP_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lead and Freedom_GDP_files/libs/quarto-html/quarto.js"></script>
<script src="Lead and Freedom_GDP_files/libs/quarto-html/popper.min.js"></script>
<script src="Lead and Freedom_GDP_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lead and Freedom_GDP_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lead and Freedom_GDP_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lead and Freedom_GDP_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lead and Freedom_GDP_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lead and Freedom_GDP_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lead and Freedom_GDP_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#empirical-exercise-8.1-stock-and-watson" id="toc-empirical-exercise-8.1-stock-and-watson" class="nav-link active" data-scroll-target="#empirical-exercise-8.1-stock-and-watson">Empirical Exercise 8.1 Stock and Watson</a>
  <ul class="collapse">
  <li><a href="#question-8.1" id="toc-question-8.1" class="nav-link" data-scroll-target="#question-8.1">Question 8.1</a>
  <ul class="collapse">
  <li><a href="#part-a" id="toc-part-a" class="nav-link" data-scroll-target="#part-a">Part A</a></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b">Part B</a></li>
  <li><a href="#part-c" id="toc-part-c" class="nav-link" data-scroll-target="#part-c">Part C</a></li>
  <li><a href="#part-d" id="toc-part-d" class="nav-link" data-scroll-target="#part-d">Part D</a></li>
  <li><a href="#part-e" id="toc-part-e" class="nav-link" data-scroll-target="#part-e">Part E</a></li>
  <li><a href="#part-f" id="toc-part-f" class="nav-link" data-scroll-target="#part-f">Part F</a></li>
  <li><a href="#part-g" id="toc-part-g" class="nav-link" data-scroll-target="#part-g">Part G</a></li>
  <li><a href="#part-h" id="toc-part-h" class="nav-link" data-scroll-target="#part-h">Part H</a></li>
  <li><a href="#part-i" id="toc-part-i" class="nav-link" data-scroll-target="#part-i">Part I</a></li>
  </ul></li>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">Question 10</a>
  <ul class="collapse">
  <li><a href="#part-a-1" id="toc-part-a-1" class="nav-link" data-scroll-target="#part-a-1">Part A</a></li>
  <li><a href="#part-b-1" id="toc-part-b-1" class="nav-link" data-scroll-target="#part-b-1">Part B</a></li>
  <li><a href="#part-c-1" id="toc-part-c-1" class="nav-link" data-scroll-target="#part-c-1">Part C</a></li>
  <li><a href="#part-d-1" id="toc-part-d-1" class="nav-link" data-scroll-target="#part-d-1">Part D</a></li>
  <li><a href="#part-e-1" id="toc-part-e-1" class="nav-link" data-scroll-target="#part-e-1">Part E</a></li>
  <li><a href="#part-f-1" id="toc-part-f-1" class="nav-link" data-scroll-target="#part-f-1">Part F</a></li>
  <li><a href="#part-g-1" id="toc-part-g-1" class="nav-link" data-scroll-target="#part-g-1">Part G</a></li>
  <li><a href="#part-h-1" id="toc-part-h-1" class="nav-link" data-scroll-target="#part-h-1">Part H</a></li>
  <li><a href="#part-i-1" id="toc-part-i-1" class="nav-link" data-scroll-target="#part-i-1">Part I</a></li>
  <li><a href="#part-j" id="toc-part-j" class="nav-link" data-scroll-target="#part-j">Part J</a></li>
  <li><a href="#part-k" id="toc-part-k" class="nav-link" data-scroll-target="#part-k">Part K</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lead_Content and Freedom_GDP</h1>
<p class="subtitle lead">Zahid Asghar<br><br> School of Economics, QAU, Islamabad</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="empirical-exercise-8.1-stock-and-watson" class="level1">
<h1>Empirical Exercise 8.1 Stock and Watson</h1>
<p>Answer the following questions using <code>R</code>. When necessary, please write answers in the same document (knitted <code>Rmd</code> to <code>html</code> or <code>pdf</code>, typed <code>.doc(x)</code>, or handwritten) as your answers to the above questions. Be sure to include (email or print an <code>.R</code> file, or show in your knitted <code>markdown</code>) your code and the outputs of your code with the rest of your answers. I am using this post material from <a href="http://metricsf21.classes.ryansafner.com">Ryan Safner</a></p>
<section id="question-8.1" class="level2">
<h2 class="anchored" data-anchor-id="question-8.1">Question 8.1</h2>
<ul>
<li><a href="http://metricsf21.classes.ryansafner.com/data/LeadMortality.csv"><i class="fas fa-table"></i> <code>LeadMortality.csv</code></a></li>
</ul>
<p>Lead is toxic, particularly for young children, and for this reason government regulations severely restrict the amount of lead in our environment. In the early part of the 20<sup>th</sup> century, the underground water pipes in many U.S. cities contained lead, and lead from these pipes leached into drinking water. This exercise will have you investigate the effect of these lead pipes on infant mortality. This dataset contains data on:</p>
<table class="table">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>infrate</code></td>
<td>infant mortality rate (deaths per 100 in population)</td>
</tr>
<tr class="even">
<td><code>lead</code></td>
<td><span class="math inline">\(=1\)</span> if city has lead water pipes, <span class="math inline">\(=0\)</span> if did not have lead pipes</td>
</tr>
<tr class="odd">
<td><code>pH</code></td>
<td>water pH</td>
</tr>
</tbody>
</table>
<p>and several demographic variables for 172 U.S. cities in 1900.</p>
<section id="part-a" class="level3">
<h3 class="anchored" data-anchor-id="part-a">Part A</h3>
<p>Part A</p>
<p><strong>Using <code>R</code> to examine the data, find the average infant mortality rate for cities with lead pipes and for cities without lead pipes. Calculate the difference, and run a</strong> <span class="math inline">\(t\)</span>-test to determine if this difference is statistically significant.</p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load tidyverse</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># read in data</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>lead <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"lead_mortality.dta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># mean of infrate for cities with lead</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mean_lead <span class="ot">&lt;-</span> lead <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(lead <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="fu">mean</span>(infrate)) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>() <span class="co"># to save as number</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># look at it</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>mean_lead</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4032576</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># mean of infrate for cities with no lead</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>mean_no_lead <span class="ot">&lt;-</span> lead <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(lead <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="fu">mean</span>(infrate)) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>() <span class="co"># to save as number</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># look at it</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>mean_no_lead</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3811679</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># take difference</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mean_lead <span class="sc">-</span> mean_no_lead</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02208973</code></pre>
</div>
</div>
<p>Cities with lead pipes have an infant mortality rate of 0.40, and cities without lead pipes have an infant mortality rate of 0.38. So the difference is 0.02.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run t-test of difference</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(infrate <span class="sc">~</span> lead, <span class="at">data =</span> lead)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  infrate by lead
t = -0.90387, df = 109.29, p-value = 0.3681
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.07052551  0.02634606
sample estimates:
mean in group 0 mean in group 1 
      0.3811679       0.4032576 </code></pre>
</div>
</div>
<p>We get a <span class="math inline">\(t\)</span>-statistic of <span class="math inline">\(-0.90\)</span> and a <span class="math inline">\(p\)</span>-value of <span class="math inline">\(0.3681\)</span>, so the difference is <em>not</em> statistically significant.</p>
<hr>
</section>
<section id="part-b" class="level3">
<h3 class="anchored" data-anchor-id="part-b">Part B</h3>
<p><strong>Run a regression of <code>infrate</code> on <code>lead</code>, and write down the estimated regression equation. Use the regression coefficients to find:</strong></p>
<ul>
<li>the average infant mortality rate for cities with lead pipes</li>
<li>the average infant mortality rate for cities without lead pipes</li>
<li>the difference between the averages for cities with or without lead pipes</li>
</ul>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lead_reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(infrate <span class="sc">~</span> lead, <span class="at">data =</span> lead)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lead_reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = infrate ~ lead, data = lead)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.27141 -0.10643 -0.01238  0.07528  0.44121 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.38117    0.02042  18.669   &lt;2e-16 ***
lead         0.02209    0.02475   0.892    0.373    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1514 on 170 degrees of freedom
Multiple R-squared:  0.004662,  Adjusted R-squared:  -0.001193 
F-statistic: 0.7963 on 1 and 170 DF,  p-value: 0.3735</code></pre>
</div>
</div>
<p><span class="math display">\[\widehat{\text{Infrate}_i} = 0.38+0.02 \, \text{Lead}_i\]</span></p>
<ul>
<li>Cities <em>without</em> lead pipes have an infant mortality rate of 0.38 <span class="math inline">\((\hat{\beta_0})\)</span></li>
<li>Cities <em>with</em> lead pipes have an infant mortality rate of <span class="math inline">\(0.38+0.02=0.40\)</span> <span class="math inline">\((\hat{\beta_0}+\hat{\beta_1})\)</span></li>
<li>The difference is <span class="math inline">\(0.02\)</span> <span class="math inline">\((\hat{\beta_3})\)</span></li>
</ul>
<hr>
</section>
<section id="part-c" class="level3">
<h3 class="anchored" data-anchor-id="part-c">Part C</h3>
<p><strong>Does the pH of the water matter? Include <code>ph</code> in your regression from part B. Write down the estimated regression equation, and interpret each coefficient (note there is no interaction effect here). What happens to the estimate on <code>lead</code>?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lead_reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(infrate <span class="sc">~</span> lead <span class="sc">+</span> ph, <span class="at">data =</span> lead)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lead_reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = infrate ~ lead + ph, data = lead)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.27074 -0.09140 -0.01517  0.07909  0.34222 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.17817    0.10676  11.035  &lt; 2e-16 ***
lead         0.04993    0.02177   2.294    0.023 *  
ph          -0.11143    0.01472  -7.570 2.31e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1312 on 169 degrees of freedom
Multiple R-squared:  0.2567,    Adjusted R-squared:  0.2479 
F-statistic: 29.18 on 2 and 169 DF,  p-value: 1.299e-11</code></pre>
</div>
</div>
<p><span class="math display">\[\widehat{\text{Infrate}_i}=1.17+0.05 \, \text{Lead}_i-0.11 \, \text{pH}_i\]</span></p>
<ul>
<li><span class="math inline">\(\hat{\beta_0}:\)</span> the infant mortality rate for cities with a pH of 0, holding the type of pipe constant is 1.17</li>
<li><span class="math inline">\(\hat{\beta_1}\)</span>: the infant mortality rate for cities with lead pipes is 0.05 higher than cities without lead pipes, holding pH constant</li>
<li><span class="math inline">\(\hat{\beta_2}\)</span>: the infant mortality rate falls by 0.11 for every increase of 1 in the city water’s pH (less acidic), holding the type of pipe constant</li>
</ul>
<p>The estimate on <code>lead</code> doubled and became significant at the 5% level.</p>
<hr>
</section>
<section id="part-d" class="level3">
<h3 class="anchored" data-anchor-id="part-d">Part D</h3>
<p><strong>The amount of lead leached from lead pipes normally depends on the chemistry of the water running through the pipes: the more acidic the water (lower pH), the more lead is leached. Create an interaction term between lead and pH, and run a regression of <code>infrate</code> on <code>lead</code>, <code>pH</code>, and your interaction term. Write down the estimated regression equation. Is this interaction significant?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lead_reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(infrate <span class="sc">~</span> lead <span class="sc">+</span> ph <span class="sc">+</span> lead<span class="sc">:</span>ph, <span class="at">data =</span> lead)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lead_reg3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = infrate ~ lead + ph + lead:ph, data = lead)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.27492 -0.09502 -0.00266  0.07965  0.35139 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.91890    0.17447   5.267  4.2e-07 ***
lead         0.46180    0.22122   2.087  0.03835 *  
ph          -0.07518    0.02427  -3.098  0.00229 ** 
lead:ph     -0.05686    0.03040  -1.871  0.06312 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1303 on 168 degrees of freedom
Multiple R-squared:  0.2719,    Adjusted R-squared:  0.2589 
F-statistic: 20.91 on 3 and 168 DF,  p-value: 1.467e-11</code></pre>
</div>
</div>
<p><span class="math display">\[\widehat{\text{Infrate}_i}=0.92+0.46 \, \text{Lead}_i-0.08 \, \text{pH}_i- \, 0.06 \, (\text{Lead} \times \text{pH})\]</span></p>
<p>We see that this interaction is just barely insignificant, with a <span class="math inline">\(p\)</span>-value of 0.06.</p>
<hr>
</section>
<section id="part-e" class="level3">
<h3 class="anchored" data-anchor-id="part-e">Part E</h3>
<p><strong>What we actually have are two different regression lines. Visualize this with a scatterplot between <code>infrate</code></strong> <span class="math inline">\((Y)\)</span> and <code>ph</code> <span class="math inline">\((X)\)</span> by <code>lead</code>.</p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lead_scatter <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> lead)<span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> ph,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> infrate)<span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">as.factor</span>(lead)))<span class="sc">+</span> <span class="co"># making it a factor makes color discrete rather than continuous!</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># now I'm just making it pretty</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># changing color</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_viridis_d</span>(<span class="st">"Pipes"</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"Not Lead"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Lead"</span>))<span class="sc">+</span> <span class="co"># changing labels for colors</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"pH"</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Infant Mortality Rate"</span>)<span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_family =</span> <span class="st">"Fira Sans Condensed"</span>,</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">base_size=</span><span class="dv">20</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>lead_scatter</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lead-and-Freedom_GDP_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>lead_scatter <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>lead, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">lead =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"Not Lead"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                                                     <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Lead"</span>)))<span class="sc">+</span> <span class="co"># change facet titles</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">color =</span> F) <span class="co"># hide other legend</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lead-and-Freedom_GDP_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="part-f" class="level3">
<h3 class="anchored" data-anchor-id="part-f">Part F</h3>
<p><strong>Do the two regression lines have the same intercept? The same slope? Use the original regression in part D to test these possibilities.</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<p><span class="math inline">\(\beta_1\)</span> (on <code>lead</code>) measures the difference in intercept between the lead &amp; no lead regression lines. So we would want to test:</p>
<p><span class="math display">\[\begin{align*}
    H_0: &amp; \beta_1=0\\
    H_a: &amp; \beta_1 \neq 0\\
\end{align*}\]</span></p>
<p>The <code>R</code> output tells us <span class="math inline">\(\hat{\beta_1}\)</span> is <span class="math inline">\(0.46\)</span> with a standard error of 0.22, so the <span class="math inline">\(t\)</span>-statistic for this test is <span class="math inline">\(2.09\)</span> with a <span class="math inline">\(p\)</span>-value of 0.04, so there is a statistically significant difference at the 5% level.</p>
<p><span class="math inline">\(\beta_3\)</span> (on the interaction term) measures the difference in slope between the lead &amp; no lead regression lines. So we would want to test:</p>
<p>$$<span class="math display">\[\begin{align*}


    H_0: &amp; \beta_3=0\\
    H_a: &amp; \beta_3 \neq 0\\
\end{align*}\]</span>$$</p>
<p>The output tells us <span class="math inline">\(\hat{\beta_3}\)</span> is <span class="math inline">\(-0.06\)</span> with a standard error of 0.3, so the <span class="math inline">\(t\)</span>-statistic for this test is <span class="math inline">\(-1.87\)</span> with a <span class="math inline">\(p\)</span>-value of <span class="math inline">\(0.06\)</span>, so there is not a statistically significant difference at the 5% level.</p>
<p>Therefore, they have <em>difference</em> intercepts, and the <em>same</em> slopes, statistically.</p>
<hr>
</section>
<section id="part-g" class="level3">
<h3 class="anchored" data-anchor-id="part-g">Part G</h3>
<p><strong>Take your regression equation from part D and rewrite it as two separate regression equations (one for no lead and one for lead). Interpret the coefficients for each.</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<p>For no lead (<code>lead=0</code>):</p>
<p><span class="math display">\[\begin{align*}
    \widehat{Infrate}&amp;=0.92+0.46 \, Lead-0.08 \, pH-0.06\, (Lead \times pH)\\
        &amp;=0.92+0.46(\mathbf{0})-0.08pH-0.06((\mathbf{0}) \times pH)\\
        &amp;=0.92-0.08 \, pH\\
\end{align*}\]</span></p>
<p>For lead (<code>lead=1</code>):</p>
<p>$$<span class="math display">\[\begin{align*}


    \widehat{Infrate}&amp;=0.92+0.46 \, Lead-0.08 \, pH-0.06\, (Lead \times pH)\\
        &amp;=0.92+0.46(\mathbf{1})-0.08pH-0.06((\mathbf{1}) \times pH)\\
        &amp;=(0.92+0.46)+(-0.08-0.06) \, pH\\
        &amp;=1.30-0.14 \, pH\\
\end{align*}\]</span>$$</p>
<p>Cities without lead pipes have an infant mortality rate of <span class="math inline">\(0.92\)</span> <span class="math inline">\((\hat{\beta_0}\)</span> from reg 1) vs.&nbsp;cities with lead pipes have an infant mortality rate of <span class="math inline">\(1.30\)</span> (<span class="math inline">\(\hat{\beta_0}\)</span> from reg 2). For every additional unit of pH, the infant mortality rate of a city without lead pipes would decrease by 0.06 <span class="math inline">\((\hat{\beta_1}\)</span> from reg 1) vs.&nbsp;a city with lead pipes which would see a fall of 0.14.</p>
<p>So again, we can see the difference in infant mortality rates between cities with lead pipes vs.&nbsp;those that don’t, with a water pH of 0 is <span class="math inline">\(1.30-0.92=\$0.38\)</span>, <span class="math inline">\((\hat{\beta_0}\)</span> from the regression in (part d)), and the cities with lead raise their infant mortality rates by <span class="math inline">\(0.14-0.08=0.06\)</span> more from each unit of pH than cities without lead do <span class="math inline">\((\hat{\beta_3})\)</span> from the regression in (part d)).</p>
<hr>
</section>
<section id="part-h" class="level3">
<h3 class="anchored" data-anchor-id="part-h">Part H</h3>
<p><strong>Double check your calculations in G are correct by running the regression in D twice, once for cities without lead pipes and once for cities with lead pipes. [Hint: <code>filter()</code> the data first, then use the filtered data for the <code>data=</code> in each regression.]</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regression for no lead</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>lead <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(lead <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lm</span>(<span class="at">data =</span> ., infrate <span class="sc">~</span> lead <span class="sc">+</span> ph <span class="sc">+</span> lead<span class="sc">:</span>ph) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = infrate ~ lead + ph + lead:ph, data = .)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.23779 -0.09733 -0.01506  0.07053  0.35139 

Coefficients: (2 not defined because of singularities)
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.91890    0.18543   4.955 7.77e-06 ***
lead              NA         NA      NA       NA    
ph          -0.07518    0.02579  -2.915  0.00521 ** 
lead:ph           NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1385 on 53 degrees of freedom
Multiple R-squared:  0.1381,    Adjusted R-squared:  0.1219 
F-statistic: 8.495 on 1 and 53 DF,  p-value: 0.005206</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regression for lead</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>lead <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(lead <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lm</span>(<span class="at">data =</span> ., infrate <span class="sc">~</span> lead <span class="sc">+</span> ph <span class="sc">+</span> lead<span class="sc">:</span>ph) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = infrate ~ lead + ph + lead:ph, data = .)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.27492 -0.08881  0.00664  0.08059  0.31646 

Coefficients: (2 not defined because of singularities)
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.38070    0.13189   10.47  &lt; 2e-16 ***
lead              NA         NA      NA       NA    
ph          -0.13204    0.01775   -7.44 1.97e-11 ***
lead:ph           NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1263 on 115 degrees of freedom
Multiple R-squared:  0.325, Adjusted R-squared:  0.3191 
F-statistic: 55.36 on 1 and 115 DF,  p-value: 1.967e-11</code></pre>
</div>
</div>
<hr>
</section>
<section id="part-i" class="level3">
<h3 class="anchored" data-anchor-id="part-i">Part I</h3>
<p><strong>Use <code>huxtable</code> to make a nice output table of all of your regressions from parts B, C, and D.</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(huxtable)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">huxreg</span>(lead_reg1,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>       lead_reg2,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       lead_reg3,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">coefs =</span> <span class="fu">c</span>(<span class="st">"Constant"</span> <span class="ot">=</span> <span class="st">"(Intercept)"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Lead Pipes"</span> <span class="ot">=</span> <span class="st">"lead"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"pH"</span> <span class="ot">=</span> <span class="st">"ph"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Lead * pH"</span> <span class="ot">=</span> <span class="st">"lead:ph"</span>),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">statistics =</span> <span class="fu">c</span>(<span class="st">"N"</span> <span class="ot">=</span> <span class="st">"nobs"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"R-Squared"</span> <span class="ot">=</span> <span class="st">"r.squared"</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"SER"</span> <span class="ot">=</span> <span class="st">"sigma"</span>),</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">number_format =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-10">
<colgroup><col><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1)</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(2)</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3)</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Constant</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.38 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1.18 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.92 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.02)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.11)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.17)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Lead Pipes</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.02&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.05 *&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.46 *&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.02)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.02)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.22)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">pH</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.11 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.08 **&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.01)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.02)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Lead * pH</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.06&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.03)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">172&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">172&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">172&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R-Squared</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.00&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.26&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.27&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">SER</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.15&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.13&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.13&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th colspan="4" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>
</tbody></table>

</div>
</div>
<hr>
</section>
</section>
<section id="question-10" class="level2">
<h2 class="anchored" data-anchor-id="question-10">Question 10</h2>
<ul>
<li><a href="http://metricsf21.classes.ryansafner.com/data/freedom.csv"><i class="fas fa-table"></i> <code>freedom.csv</code></a></li>
</ul>
<p>Let’s look at economic freedom and GDP per capita using some data I sourced from <a href="https://gapminder.org/tools">Gapminder</a><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, <a href="https://freedomhouse.org/content/freedom-world-data-and-resources">Freedom House</a><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> and <a href="https://www.fraserinstitute.org/economic-freedom/dataset?geozone=world&amp;year=2016&amp;page=dataset">Fraser Institute Data</a><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> and cleaned up for you, with the following variables:</p>
<table class="table">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Country</code></td>
<td>Name of country</td>
</tr>
<tr class="even">
<td><code>ISO</code></td>
<td>Code of country (good for plotting)</td>
</tr>
<tr class="odd">
<td><code>econ_freedom</code></td>
<td>Economic Freedom Index score (2016) from 1 (least) to 10 (most free)</td>
</tr>
<tr class="even">
<td><code>pol_freedom</code></td>
<td>Political freedom index score (2018) from 1 (least) top 10 (most free)</td>
</tr>
<tr class="odd">
<td><code>gdp_pc</code></td>
<td>GDP per capita (2018 USD)</td>
</tr>
<tr class="even">
<td><code>continent</code></td>
<td>Continent of country</td>
</tr>
</tbody>
</table>
<section id="part-a-1" class="level3">
<h3 class="anchored" data-anchor-id="part-a-1">Part A</h3>
<p><strong>Does economic freedom affect GDP per capita? Create a scatterplot of <code>gdp_pc</code> (<code>Y</code>) against <code>econ_freedom</code> (<code>x</code>). Does the effect appear to be linear or nonlinear?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>freedom <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"freedom.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>freedom_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> freedom)<span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> econ_freedom,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> gdp_pc)<span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> continent))<span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>dollar)<span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Economic Freedom Score (0-10)"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"GDP per Capita"</span>)<span class="sc">+</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_family =</span> <span class="st">"Fira Sans Condensed"</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">base_size =</span> <span class="dv">20</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>freedom_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lead-and-Freedom_GDP_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The effect appears to be nonlinear.</p>
<hr>
</section>
<section id="part-b-1" class="level3">
<h3 class="anchored" data-anchor-id="part-b-1">Part B</h3>
<p><strong>Run a simple regression of <code>gdp_pc</code> on <code>econ_freedom</code>. Write out the estimated regression equation. What is the marginal effect of <code>econ_freedom</code> on <code>gdp_pc</code>?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>freedom_reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(gdp_pc <span class="sc">~</span> econ_freedom, <span class="at">data =</span> freedom)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(freedom_reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gdp_pc ~ econ_freedom, data = freedom)

Residuals:
   Min     1Q Median     3Q    Max 
-24612 -10511  -3707   9727  65562 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -86400      13362  -6.466 2.85e-09 ***
econ_freedom    14704       1935   7.599 1.06e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15880 on 110 degrees of freedom
Multiple R-squared:  0.3442,    Adjusted R-squared:  0.3383 
F-statistic: 57.74 on 1 and 110 DF,  p-value: 1.063e-11</code></pre>
</div>
</div>
<hr>
</section>
<section id="part-c-1" class="level3">
<h3 class="anchored" data-anchor-id="part-c-1">Part C</h3>
<p><strong>Let’s try a quadratic model. Run a quadratic regression of <code>gdp_pc</code> on <code>econ_freedom</code>. Write out the estimated regression equation.</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>freedom_reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(gdp_pc <span class="sc">~</span> econ_freedom <span class="sc">+</span> <span class="fu">I</span>(econ_freedom<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> freedom)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(freedom_reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gdp_pc ~ econ_freedom + I(econ_freedom^2), data = freedom)

Residuals:
   Min     1Q Median     3Q    Max 
-30174  -8366   -647   2980  65158 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         280417      79511   3.527 0.000617 ***
econ_freedom        -96619      23908  -4.041 9.93e-05 ***
I(econ_freedom^2)     8327       1783   4.669 8.67e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 14560 on 109 degrees of freedom
Multiple R-squared:  0.4535,    Adjusted R-squared:  0.4435 
F-statistic: 45.23 on 2 and 109 DF,  p-value: 4.986e-15</code></pre>
</div>
</div>
<hr>
</section>
<section id="part-d-1" class="level3">
<h3 class="anchored" data-anchor-id="part-d-1">Part D</h3>
<p><strong>Add the quadratic regression to your scatterplot.</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>freedom_plot <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> <span class="st">"y~x+I(x^2)"</span>, <span class="at">color =</span> <span class="st">"green"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lead-and-Freedom_GDP_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="part-e-1" class="level3">
<h3 class="anchored" data-anchor-id="part-e-1">Part E</h3>
<p><strong>What is the marginal effect of <code>econ_freedom</code> on <code>gdp_pc</code>?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<p>The marginal effect can be found by taking the derivative of the regression with respect to <code>econ_freedom</code> (or recalling the rule):</p>
<p><span class="math display">\[\begin{align*}
    \frac{d \, Y}{d \, X} &amp;= \beta_1+2\beta_2 X\\
    \frac{d \, GDPpc}{d \, econfreedom} &amp;= -96618+2(8327)econfreedom\, econ\\
    &amp;=-96618+16654 \, econfreedom\\
    \end{align*}\]</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if you want to calculate it in R</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>freedom_reg2_tidy <span class="ot">&lt;-</span> <span class="fu">tidy</span>(freedom_reg2)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>freedom_beta_1 <span class="ot">&lt;-</span> freedom_reg2_tidy <span class="sc">%&gt;%</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"econ_freedom"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(estimate)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>freedom_beta_2 <span class="ot">&lt;-</span> freedom_reg2_tidy <span class="sc">%&gt;%</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"I(econ_freedom^2)"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(estimate)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="co"># freedom_beta_1+2*freedom_beta_2* # number</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<hr>
</section>
<section id="part-f-1" class="level3">
<h3 class="anchored" data-anchor-id="part-f-1">Part F</h3>
<p><strong>As a quadratic model, this relationship should predict an<code>econ_freedom</code> score where <code>gdp_pc</code> is at a <em>minimum</em>. What is that minimum Economic Freedom score, and what is the associated GDP per capita?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<p>We can set the derivative equal to 0, or you can just remember the formula and plug in the parameters:</p>
<p>$$<span class="math display">\[\begin{align*}


    \frac{d Y}{d X}  &amp;= \beta_1+2\beta_2 X\\
    0 &amp;=\beta_1+2\beta_2 X\\
    -\beta_1&amp;=2\beta_2 X\\
    -\frac{1}{2} \times \frac{\beta_1}{\beta_2}&amp;=econfreedom^*\\
    -\frac{1}{2} \times\frac{(-96618)}{(8327)} &amp;= econfreedom^*\\
    -\frac{1}{2} \times -11.603 &amp; \approx econfreedom^*\\
    5.801 &amp; \approx econfreedom ^*\\
\end{align*}\]</span>$$</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to calculate in R</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>min <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.5</span><span class="sc">*</span>(freedom_beta_1<span class="sc">/</span>freedom_beta_2)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.801793</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># let's visualize on the scatterplot</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>freedom_plot <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> <span class="st">"y~x+I(x^2)"</span>, <span class="at">color =</span> <span class="st">"green"</span>)<span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> min, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_label</span>(<span class="at">x =</span> min, <span class="at">y =</span> <span class="dv">75000</span>, <span class="at">label =</span> <span class="fu">round</span>(min,<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lead-and-Freedom_GDP_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="part-g-1" class="level3">
<h3 class="anchored" data-anchor-id="part-g-1">Part G</h3>
<p><strong>Run a cubic model to see if we should keep going up in polynomials. Write out the estimated regression equation. Should we add a cubic term?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>freedom_reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(gdp_pc <span class="sc">~</span> econ_freedom <span class="sc">+</span> <span class="fu">I</span>(econ_freedom<span class="sc">^</span><span class="dv">2</span>)<span class="sc">+</span> <span class="fu">I</span>(econ_freedom<span class="sc">^</span><span class="dv">3</span>),</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> freedom)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(freedom_reg3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gdp_pc ~ econ_freedom + I(econ_freedom^2) + I(econ_freedom^3), 
    data = freedom)

Residuals:
   Min     1Q Median     3Q    Max 
-30290  -8451   -493   3356  64636 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)        531003.4   470172.4   1.129    0.261
econ_freedom      -211572.5   213908.4  -0.989    0.325
I(econ_freedom^2)   25674.4    32127.4   0.799    0.426
I(econ_freedom^3)    -862.2     1594.2  -0.541    0.590

Residual standard error: 14610 on 108 degrees of freedom
Multiple R-squared:  0.455, Adjusted R-squared:  0.4399 
F-statistic: 30.05 on 3 and 108 DF,  p-value: 3.318e-14</code></pre>
</div>
</div>
<p>There’s no good theoretical reason why we should expect economic freedom to “change direction” twice - go down, then up, then down again - in its effect on GDP.</p>
<p>Statistically, we can see that <span class="math inline">\(\hat{\beta_3}\)</span> on <code>I(econ_freedom^3)</code> is not significant (<code>p-value</code> is <code>0.590</code>), so we should <em>not</em> include the cubic term.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># let's visualize it on the scatterplot</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>freedom_plot<span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> <span class="st">"y~x+I(x^2)"</span>, <span class="at">color =</span> <span class="st">"green"</span>)<span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> <span class="st">"y~x+I(x^2)+I(x^3)"</span>, <span class="at">color =</span> <span class="st">"orange"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lead-and-Freedom_GDP_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="part-h-1" class="level3">
<h3 class="anchored" data-anchor-id="part-h-1">Part H</h3>
<p><strong>Another way we can <em>test</em> for non-linearity is to run an</strong> <span class="math inline">\(F\)</span>-test on all non-linear variables - i.e.&nbsp;the quadratic term and the cubic term <span class="math inline">\((\hat{\beta_2}\)</span> and <span class="math inline">\(\hat{\beta_3}\)</span>) and test against the null hypothesis that: <span class="math display">\[H_0: \hat{\beta_2} = \hat{\beta_3} = 0\]</span></p>
<p><strong>Run this joint hypothesis test, and what can you conclude?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run F test</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(freedom_reg3, <span class="fu">c</span>(<span class="st">"I(econ_freedom^2)"</span>, <span class="st">"I(econ_freedom^3)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The null hypothesis is that the polynomial terms (quadratic and cubic) jointly do not matter (and the relationship is therefore linear). We have sufficient evidence to reject that hypothesis (<code>p-value</code> is very small). Thus, the relationship is in fact <em>not</em> linear.</p>
<hr>
</section>
<section id="part-i-1" class="level3">
<h3 class="anchored" data-anchor-id="part-i-1">Part I</h3>
<p><strong>Instead of a polynomial model, try out a logarithmic model. It is hard to interpret percent changes on an index, but it is easy to understand percent changes in GDP per capita, so run a <em>log-linear</em> regression. Write out the estimated regression equation. What is the marginal effect of <code>econ_freedom</code>?</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># log linear model </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>freedom_reg4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(gdp_pc) <span class="sc">~</span> econ_freedom, <span class="at">data =</span> freedom)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(freedom_reg4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(gdp_pc) ~ econ_freedom, data = freedom)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1046 -0.9507 -0.0533  0.9021  3.3551 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -0.2953     1.0323  -0.286    0.775    
econ_freedom   1.2889     0.1495   8.621 5.53e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.227 on 110 degrees of freedom
Multiple R-squared:  0.4032,    Adjusted R-squared:  0.3978 
F-statistic: 74.32 on 1 and 110 DF,  p-value: 5.525e-14</code></pre>
</div>
</div>
<p>For every 1 point increase on the economic freedom index, a country’s GDP per capita increases by <span class="math inline">\(1.2889 \times 100\%=128.90\%\)</span></p>
<hr>
</section>
<section id="part-j" class="level3">
<h3 class="anchored" data-anchor-id="part-j">Part J</h3>
<p><strong>Make a scatterplot of your log-linear model with a regression line.</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>log_freedom_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> freedom)<span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> econ_freedom,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="fu">log</span>(gdp_pc))<span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> continent))<span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Economic Freedom Score (0-10)"</span>,</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Log GDP per Capita"</span>)<span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_family =</span> <span class="st">"Fira Sans Condensed"</span>,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">base_size =</span> <span class="dv">20</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>log_freedom_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Lead-and-Freedom_GDP_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="part-k" class="level3">
<h3 class="anchored" data-anchor-id="part-k">Part K</h3>
<p><strong>Put all of your results together in a regression output table with <code>huxtable</code> from your answers in questions B, C, G, and H.</strong></p>
<hr>
<!--WRITE YOUR ANSWERS BELOW -->
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">huxreg</span>(<span class="st">"GDP per Capita"</span> <span class="ot">=</span> freedom_reg1,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>       <span class="st">"GDP per Capita"</span> <span class="ot">=</span> freedom_reg2,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>       <span class="st">"Log(GDP per Capita)"</span> <span class="ot">=</span> freedom_reg3,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">coefs =</span> <span class="fu">c</span>(<span class="st">"Constant"</span> <span class="ot">=</span> <span class="st">"(Intercept)"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Economic Freedom Score (0-10)"</span> <span class="ot">=</span> <span class="st">"econ_freedom"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Economic Freedom Squared"</span> <span class="ot">=</span> <span class="st">"I(econ_freedom^2)"</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Economic Freedom Cubed"</span> <span class="ot">=</span> <span class="st">"I(econ_freedom^3)"</span>),</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">statistics =</span> <span class="fu">c</span>(<span class="st">"N"</span> <span class="ot">=</span> <span class="st">"nobs"</span>,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"R-Squared"</span> <span class="ot">=</span> <span class="st">"r.squared"</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"SER"</span> <span class="ot">=</span> <span class="st">"sigma"</span>),</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">number_format =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-24">
<colgroup><col><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">GDP per Capita</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">GDP per Capita</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Log(GDP per Capita)</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Constant</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-86400.07 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">280416.48 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">531003.39&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(13361.77)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(79511.27)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(470172.38)</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Economic Freedom Score (0-10)</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">14704.30 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-96618.52 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-211572.48&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1935.13)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(23908.06)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(213908.44)</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Economic Freedom Squared</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8326.61 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">25674.41&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1783.32)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(32127.38)</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Economic Freedom Cubed</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-862.15&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1594.20)</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">112&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">112&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">112&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R-Squared</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.34&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.45&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.45&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">SER</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">15881.92&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">14564.43&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">14611.94&nbsp;</td></tr>
<tr>
<th colspan="4" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>
</tbody></table>

</div>
</div>
</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>GDP per capita (2018)<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Political freedom score (2018)<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>Economic Freedom score (2016)<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>